### PR TITLE
Add spring example

### PR DESCRIPTION
**Pull request by librarianmage**
Closes https://github.com/ualibweb/mod-calendar/issues/9

### CODE REVIEW

**Review by ncovercash — CHANGES_REQUESTED** [review]
Please change the permissions on the Perl sample back to the original. Other than that, everything looks great!

**Comment by ncovercash** [comment]
Also, please add your sample module to the list/information in the README so others can find it easily!

**Comment by librarianmage** [comment]
> Also, please add your sample module to the list/information in the README so others can find it easily!

idk where to put it in the readme

**Comment by ncovercash** [comment]
@librarianmage I'd suggest with the other hello-* modules; whatever feels natural!

**Review by ncovercash — APPROVED** [review]

**Comment by ncovercash** [comment]
Mind also adding something [here](https://github.com/ualibweb/folio-sample-modules#javavertx-and-nodejs)?   Can be before or something, but I'd like to make a note about the ongoing transition to the spring way, with the various technologies we've been using instead of RMB/RAML/Vert.x

**Comment by librarianmage** [comment]
> Mind also adding something [here](https://github.com/ualibweb/folio-sample-modules#javavertx-and-nodejs)? Can be before or something, but I'd like to make a note about the ongoing transition to the spring way, with the various technologies we've been using instead of RMB/RAML/Vert.x

Do you have any suggested wording? I'm struggling to word something up

**Comment by ncovercash** [comment]
> > Mind also adding something [here](https://github.com/ualibweb/folio-sample-modules#javavertx-and-nodejs)? Can be before or something, but I'd like to make a note about the ongoing transition to the spring way, with the various technologies we've been using instead of RMB/RAML/Vert.x
> 
> Do you have any suggested wording? I'm struggling to word something up

I got u

**Comment by ncovercash** [comment]
@librarianmage what do you think of that?

**Comment by ncovercash** [comment]
I can't request a review from you for some reason

**Comment by librarianmage** [comment]
Looks good to me!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Noah Overcash ***@***.***>
Sent: Thursday, February 3, 2022 5:15:41 PM
To: ualibweb/folio-sample-modules ***@***.***>
Cc: Ray Arndorfer ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ualibweb/folio-sample-modules] Add spring example (PR #1)


I can't request a review from you for some reason

—
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fualibweb%2Ffolio-sample-modules%2Fpull%2F1%23issuecomment-1029489152&data=04%7C01%7Crarndorfer%40ua.edu%7C7c719bf4474f43b2953d08d9e76b19b9%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637795269469607076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3VQXe9MEiNP3%2FwNWVlqRhHjSMa4qp%2FrXlFS5AVsvUEg%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAC6P74YRGXXE3UNYCHIRJPLUZMEB3ANCNFSM5M7BXVYA&data=04%7C01%7Crarndorfer%40ua.edu%7C7c719bf4474f43b2953d08d9e76b19b9%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637795269469607076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VcISbzqIP24Uf7rSMnsWrPUJWbm6ilY4OUtVihpOdgg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crarndorfer%40ua.edu%7C7c719bf4474f43b2953d08d9e76b19b9%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637795269469607076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qZvKq8KsV1r1Q0R48sYxUfbbRyHWLUfPmbT6JX%2FVnHk%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crarndorfer%40ua.edu%7C7c719bf4474f43b2953d08d9e76b19b9%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637795269469607076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6xKX2jiIzDTEEujraYEI5OikPPNgjzydEQ8L5IFLdNo%3D&reserved=0>.

**Comment by ncovercash** [comment]
@librarianmage cool!  Feel free to do a PR from this branch to FOLIO's master!

**Comment by librarianmage** [comment]
https://github.com/folio-org/folio-sample-modules/pull/24

**Pull request merged**
